package per.iys.crm.settings.mapper;

import org.apache.ibatis.annotations.Mapper;
import per.iys.crm.settings.domain.User;

import java.util.List;
import java.util.Map;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 17 20:17:15 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 17 20:17:15 CST 2022
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 17 20:17:15 CST 2022
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 17 20:17:15 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 17 20:17:15 CST 2022
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 17 20:17:15 CST 2022
     */
    int updateByPrimaryKey(User row);

    /**
     * 根据帐号密码查询用户
     *
     * @param map
     * @return 用户信息
     */
    User selectUserByLoginActAndLoginPwd(Map<String, Object> map);

    /**
     * 查询所有的用户
     *
     * @return 所用用户
     */
    List<User> selectAllUsers();
}